import type { Metadata } from "next";
import { Inter, Galdeano, Poppins } from "next/font/google"
import "./globals.css";



const inter = Inter({
  subsets:["latin"],
  variable:"--font-inter",
})

const galdeano = Galdeano({
  weight:"400",
  subsets:["latin"],
  variable:"--font-galdeano",
})

const poppins= Poppins({
  weight:"400",
  subsets:["latin"],
  variable:"--font-poppins",
})

export const metadata: Metadata = {
  title: "LYTEPEN WEB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${galdeano.variable} ${inter.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
